
export type UsersActionType = 
'GETTING_USER_PROFILE' |
'GETTING_USER_PROFILE_SUCCESS' |
'GETTING_USER_PROFILE_FAILURE' |

'GETTING_USER_STATISTICS' |
'GETTING_USER_STATISTICS_SUCCESS' |
'GETTING_USER_STATISTICS_FAILURE' |

'GETTING_USER_STATISTICS_WITH_BEST_SCORE' |
'GETTING_USER_STATISTICS_WITH_BEST_SCORE_SUCCESS' |
'GETTING_USER_STATISTICS_WITH_BEST_SCORE_FAILURE' |

'GETTING_USER_STATISTICS_WITH_MOST_POSTS' |
'GETTING_USER_STATISTICS_WITH_MOST_POSTS_SUCCESS' |
'GETTING_USER_STATISTICS_WITH_MOST_POSTS_FAILURE' |

'LOGGING_IN' |
'LOGGING_IN_SUCCESS' |
'LOGGING_IN_FAILURE' |

'LOGGING_OUT' |
'LOGGING_OUT_SUCCESS' |
'LOGGING_OUT_FAILURE' |

'CREATING_USER' |
'CREATING_USER_SUCCESS' |
'CREATING_USER_FAILURE';

const GETTING_USER_PROFILE: UsersActionType = 'GETTING_USER_PROFILE';
const GETTING_USER_PROFILE_SUCCESS: UsersActionType = 'GETTING_USER_PROFILE_SUCCESS';
const GETTING_USER_PROFILE_FAILURE: UsersActionType = 'GETTING_USER_PROFILE_FAILURE';

const GETTING_USER_STATISTICS: UsersActionType = 'GETTING_USER_STATISTICS';
const GETTING_USER_STATISTICS_SUCCESS: UsersActionType = 'GETTING_USER_STATISTICS_SUCCESS';
const GETTING_USER_STATISTICS_FAILURE: UsersActionType = 'GETTING_USER_STATISTICS_FAILURE';

const GETTING_USER_STATISTICS_WITH_BEST_SCORE: UsersActionType = 'GETTING_USER_STATISTICS_WITH_BEST_SCORE';
const GETTING_USER_STATISTICS_WITH_BEST_SCORE_SUCCESS: UsersActionType = 'GETTING_USER_STATISTICS_WITH_BEST_SCORE_SUCCESS';
const GETTING_USER_STATISTICS_WITH_BEST_SCORE_FAILURE: UsersActionType = 'GETTING_USER_STATISTICS_WITH_BEST_SCORE_FAILURE';

const GETTING_USER_STATISTICS_WITH_MOST_POSTS: UsersActionType = 'GETTING_USER_STATISTICS_WITH_MOST_POSTS';
const GETTING_USER_STATISTICS_WITH_MOST_POSTS_SUCCESS: UsersActionType = 'GETTING_USER_STATISTICS_WITH_MOST_POSTS_SUCCESS';
const GETTING_USER_STATISTICS_WITH_MOST_POSTS_FAILURE: UsersActionType = 'GETTING_USER_STATISTICS_WITH_MOST_POSTS_FAILURE';

const LOGGING_IN: UsersActionType = 'LOGGING_IN';
const LOGGING_IN_SUCCESS: UsersActionType = 'LOGGING_IN_SUCCESS';
const LOGGING_IN_FAILURE: UsersActionType = 'LOGGING_IN_FAILURE';

const LOGGING_OUT: UsersActionType = 'LOGGING_OUT';
const LOGGING_OUT_SUCCESS: UsersActionType = 'LOGGING_OUT_SUCCESS';
const LOGGING_OUT_FAILURE: UsersActionType = 'LOGGING_OUT_FAILURE';

const CREATING_USER: UsersActionType = 'CREATING_USER';
const CREATING_USER_SUCCESS: UsersActionType = 'CREATING_USER_SUCCESS';
const CREATING_USER_FAILURE: UsersActionType = 'CREATING_USER_FAILURE';

export {
  GETTING_USER_PROFILE,
  GETTING_USER_PROFILE_SUCCESS,
  GETTING_USER_PROFILE_FAILURE,

  GETTING_USER_STATISTICS,
  GETTING_USER_STATISTICS_SUCCESS,
  GETTING_USER_STATISTICS_FAILURE,

  GETTING_USER_STATISTICS_WITH_BEST_SCORE,
  GETTING_USER_STATISTICS_WITH_BEST_SCORE_SUCCESS,
  GETTING_USER_STATISTICS_WITH_BEST_SCORE_FAILURE,

  GETTING_USER_STATISTICS_WITH_MOST_POSTS,
  GETTING_USER_STATISTICS_WITH_MOST_POSTS_SUCCESS,
  GETTING_USER_STATISTICS_WITH_MOST_POSTS_FAILURE,

  LOGGING_IN,
  LOGGING_IN_SUCCESS,
  LOGGING_IN_FAILURE,

  LOGGING_OUT,
  LOGGING_OUT_SUCCESS,
  LOGGING_OUT_FAILURE,

  CREATING_USER,
  CREATING_USER_SUCCESS,
  CREATING_USER_FAILURE
}

const getUsersActionTypes = () => ({
  GETTING_USER_PROFILE,
  GETTING_USER_PROFILE_SUCCESS,
  GETTING_USER_PROFILE_FAILURE,

  GETTING_USER_STATISTICS,
  GETTING_USER_STATISTICS_SUCCESS,
  GETTING_USER_STATISTICS_FAILURE,

  GETTING_USER_STATISTICS_WITH_BEST_SCORE,
  GETTING_USER_STATISTICS_WITH_BEST_SCORE_SUCCESS,
  GETTING_USER_STATISTICS_WITH_BEST_SCORE_FAILURE,

  GETTING_USER_STATISTICS_WITH_MOST_POSTS,
  GETTING_USER_STATISTICS_WITH_MOST_POSTS_SUCCESS,
  GETTING_USER_STATISTICS_WITH_MOST_POSTS_FAILURE,

  LOGGING_IN,
  LOGGING_IN_SUCCESS,
  LOGGING_IN_FAILURE,

  LOGGING_OUT,
  LOGGING_OUT_SUCCESS,
  LOGGING_OUT_FAILURE,

  CREATING_USER,
  CREATING_USER_SUCCESS,
  CREATING_USER_FAILURE,
});

export default getUsersActionTypes;